<html>
<head>
    <meta charset="UTF-8">
    <title>Blog</title>
    <link rel="stylesheet" href="/css/blog.css">
    <link href="https://fonts.googleapis.com/css2?family=Kaushan+Script&family=Montserrat:ital,wght@0,400;0,700;1,300&display=swap"
          rel="stylesheet">
    <script src="https://kit.fontawesome.com/c02ef43b18.js" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.js"
            integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc="
            crossorigin="anonymous"></script>
</head>
<body>
<form action="/blog" method="post">

    <header class="header">
        <div class="container">
            <div class="header_inner">
                <a class="header_logo" href="/main">.flower</a>
                <nav class="nav">
                    <a class="nav_link" href="/aboutUs">О нас</a>
                    <a class="nav_link" href="/shop">Купить</a>
                    <a class="nav_link" href="/blog">Блог</a>
                    <a class="nav_link" href="/works">Работы</a>
                    <a class="nav_link" href="/contact">Контакты</a>
                    <a class="nav_link" href="/basket">
                        <i class="fas fa-shopping-cart"></i>
                    </a>
                    <a class="nav_link signIn" href="/signIn">
                        <i class="fas fa-user"></i>
                    </a>
                </nav>
            </div>
        </div>
    </header>

    <section class="section">
        <div class="container">
            <div class="blog">
                <div class="blog_item">
                    <div class="blog_header">
                        <a href="#">
                            <img class="blog_photo" src="/image/blogs/blog_1.png" alt="">
                        </a>
                        <div class="blog_date">
                            <div class="blog_date-day">3</div>
                            Июля
                        </div>
                    </div>
                    <div class="blog_content">
                        <div class="blog_title">
                            <a href="#">Тенденции букетов 2021</a>
                        </div>
                        <div class="blog_text">Мы не используем химические вещества для искусственного
                            сохранения свежести, потому что ценим доверие, оказанное нам нашими клиентами.
                        </div>
                    </div>
                    <div class="blog_footer">
                        <div class="blog_stat">
                        <span class="blog_stat_item">
                            <i class="far fa-eye"></i> 542</span>
                            <span class="blog_stat_item">
                            <i class="far fa-comment-dots"></i> 17</span>
                        </div>
                    </div>
                </div>
                <div class="blog_item">
                    <div class="blog_header">
                        <a href="#">
                            <img class="blog_photo" src="/image/blogs/blog_2.png" alt="">
                        </a>
                        <div class="blog_date">
                            <div class="blog_date-day">25</div>
                            Августа
                        </div>
                    </div>
                    <div class="blog_content">
                        <div class="blog_title">
                            <a href="#">Путешествие в Прованс</a>
                        </div>
                        <div class="blog_text">Мы не используем химические вещества для искусственного
                            сохранения свежести, потому что ценим доверие, оказанное нам нашими клиентами.
                        </div>
                    </div>
                    <div class="blog_footer">
                        <div class="blog_stat">
                        <span class="blog_stat_item">
                            <i class="far fa-eye"></i> 859</span>
                            <span class="blog_stat_item">
                            <i class="far fa-comment-dots"></i> 57</span>
                        </div>
                    </div>
                </div>
                <div class="blog_item">
                    <div class="blog_header">
                        <a href="#">
                            <img class="blog_photo" src="/image/blogs/blog_3.png" alt="">
                        </a>
                        <div class="blog_date">
                            <div class="blog_date-day">11</div>
                            Сентября
                        </div>
                    </div>
                    <div class="blog_content">
                        <div class="blog_title">
                            <a href="#">Что нужно, чтобы стать флористом</a>
                        </div>
                        <div class="blog_text">Мы не используем химические вещества для искусственного
                            сохранения свежести, потому что ценим доверие, оказанное нам нашими клиентами.
                        </div>
                    </div>
                    <div class="blog_footer">
                        <div class="blog_stat">
                        <span class="blog_stat_item">
                            <i class="far fa-eye"></i> 421</span>
                            <span class="blog_stat_item">
                            <i class="far fa-comment-dots"></i> 9</span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="blog">
                <div class="blog_item">
                    <div class="blog_header">
                        <a href="#">
                            <img class="blog_photo" src="/image/blogs/blog_4.png" alt="">
                        </a>
                        <div class="blog_date">
                            <div class="blog_date-day">12</div>
                            Декабря
                        </div>
                    </div>
                    <div class="blog_content">
                        <div class="blog_title">
                            <a href="#">Значение цветов</a>
                        </div>
                        <div class="blog_text">Мы не используем химические вещества для искусственного
                            сохранения свежести, потому что ценим доверие, оказанное нам нашими клиентами.
                        </div>
                    </div>
                    <div class="blog_footer">
                        <div class="blog_stat">
                        <span class="blog_stat_item">
                            <i class="far fa-eye"></i> 243</span>
                            <span class="blog_stat_item">
                            <i class="far fa-comment-dots"></i> 19</span>
                        </div>
                    </div>
                </div>
                <div class="blog_item">
                    <div class="blog_header">
                        <a href="#">
                            <img class="blog_photo" src="/image/blogs/blog_5.png" alt="">
                        </a>
                        <div class="blog_date">
                            <div class="blog_date-day">30</div>
                            Апреля
                        </div>
                    </div>
                    <div class="blog_content">
                        <div class="blog_title">
                            <a href="#">Фестиваль цветов в Нидерландах</a>
                        </div>
                        <div class="blog_text">Мы не используем химические вещества для искусственного
                            сохранения свежести, потому что ценим доверие, оказанное нам нашими клиентами.
                        </div>
                    </div>
                    <div class="blog_footer">
                        <div class="blog_stat">
                        <span class="blog_stat_item">
                            <i class="far fa-eye"></i> 712</span>
                            <span class="blog_stat_item">
                            <i class="far fa-comment-dots"></i> 56</span>
                        </div>
                    </div>
                </div>
                <div class="blog_item">
                    <div class="blog_header">
                        <a href="#">
                            <img class="blog_photo" src="/image/blogs/blog_6.png" alt="">
                        </a>
                        <div class="blog_date">
                            <div class="blog_date-day">4</div>
                            Мая
                        </div>
                    </div>
                    <div class="blog_content">
                        <div class="blog_title">
                            <a href="#">Топ 5 красивых цветочных полей мира</a>
                        </div>
                        <div class="blog_text">Мы не используем химические вещества для искусственного
                            сохранения свежести, потому что ценим доверие, оказанное нам нашими клиентами.
                        </div>
                    </div>
                    <div class="blog_footer">
                        <div class="blog_stat">
                        <span class="blog_stat_item">
                            <i class="far fa-eye"></i> 375</span>
                            <span class="blog_stat_item">
                            <i class="far fa-comment-dots"></i> 29</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

</form>
</body>
</html>