<html>
<head>
    <meta charset="UTF-8">
    <title>Contact</title>
    <link rel="stylesheet" href="/css/contact.css">
    <link href="https://fonts.googleapis.com/css2?family=Kaushan+Script&family=Montserrat:ital,wght@0,400;0,700;1,300&display=swap"
          rel="stylesheet">
    <script src="https://kit.fontawesome.com/c02ef43b18.js" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.js"
            integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc="
            crossorigin="anonymous"></script>
</head>
<body>
    <header class="header">
        <div class="container">
            <div class="header_inner">
                <a class="header_logo" href="/main">.flower</a>
                <nav class="nav">
                    <a class="nav_link" href="/aboutUs">О нас</a>
                    <a class="nav_link" href="/shop">Купить</a>
                    <a class="nav_link" href="/blog">Блог</a>
                    <a class="nav_link" href="/works">Работы</a>
                    <a class="nav_link" href="/contact">Контакты</a>
                    <a class="nav_link" href="/basket">
                        <i class="fas fa-shopping-cart"></i>
                    </a>
                    <a class="nav_link signIn" href="/signIn">
                        <i class="fas fa-user"></i>
                    </a>
                </nav>
            </div>
        </div>
    </header>

    <section class="section">
        <div class="container">
            <div class="section_header">
                <h1 class="section_title">Наша команда</h1>
            </div>
            <div class="about">
                <div class="about_item">
                    <div class="about_image">
                        <img src="/image/contact/girl1.jpg">
                    </div>
                    <div class="about_text">
                        <div class="social">
                            <a class="social_item" href="#" target="_blank">
                                <i class="fab fa-facebook-f"></i>
                            </a>
                            <a class="social_item" href="#" target="_blank">
                                <i class="fab fa-twitter"></i>
                            </a>
                            <a class="social_item" href="#" target="_blank">
                                <i class="fab fa-instagram"></i>
                            </a>
                        </div>
                    </div>
                </div>
                <div class="about_item">
                    <div class="about_image">
                        <img src="/image/contact/man1.jpg">
                    </div>
                    <div class="about_text">
                        <div class="social">
                            <a class="social_item" href="#" target="_blank">
                                <i class="fab fa-facebook-f"></i>
                            </a>
                            <a class="social_item" href="#" target="_blank">
                                <i class="fab fa-twitter"></i>
                            </a>
                            <a class="social_item" href="#" target="_blank">
                                <i class="fab fa-instagram"></i>
                            </a>
                        </div>
                    </div>
                </div>
                <div class="about_item">
                    <div class="about_image">
                        <img src="/image/contact/girl2.jpg">
                    </div>
                    <div class="about_text">
                        <div class="social">
                            <a class="social_item" href="#" target="_blank">
                                <i class="fab fa-facebook-f"></i>
                            </a>
                            <a class="social_item" href="#" target="_blank">
                                <i class="fab fa-twitter"></i>
                            </a>
                            <a class="social_item" href="#" target="_blank">
                                <i class="fab fa-instagram"></i>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="person">
                <div class="about_person">
                    <div class="text_person">
                        <p class="name">Мария Голубева</p>
                        <p>Главный флорист</p>
                        <p>Генератор криативных идей</p>
                    </div>
                </div>
                <div class="about_person">
                    <div class="text_person">
                        <p class="name">Петр Романов</p>
                        <p>Флорист</p>
                        <p>Идейный вдохновитель</p>
                    </div>
                </div>
                <div class="about_person">
                    <div class="text_person">
                        <p class="name">Анастасия Василькова</p>
                        <p>Флорист</p>
                        <p>Реализатор идей</p>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <div class="section section-map">
        <div class="container">
            <div class="map">
                <h2 class="map_title">
                    <div><i class="fas fa-map-marker-alt"></i></div>
                    <a href="https://goo.gl/maps/Byxv35cZSbsWn5B66" target="_blank">Open Map</a>
                </h2>
            </div>
        </div>
    </div>

    <footer class="footer">
        <div class="container">
            <div class="footer_inner">
                <div class="footer_col footer_col--first">
                    <div class="footer_logo">Цветы</div>
                    <div class="footer_text">
                        Адрес: ......
                        <p>График работы:
                        <li>Пн-Пт: 10:00 - 18:00</li>
                        <li>Сб: 10:00 - 16:00</li>
                        <li>Вс: выходной</li>
                        </p>
                    </div>
                    <div class="footer_social">
                        <div class="footer_social-header">
                            <b>15k folowers</b>
                        </div>
                        <div class="footer_social-content">
                            Follow us:
                            <a href="#" target="_blank">
                                <i class="fab fa-facebook"></i>
                            </a>
                            <a href="#" target="_blank">
                                <i class="fab fa-twitter"></i>
                            </a>
                            <a href="#" target="_blank">
                                <i class="fab fa-instagram"></i>
                            </a>
                        </div>
                    </div>
                    <form class="subscribe" action="/contact" method="post">
                        <input class="subscribe_input" type="email" name="name" placeholder="email">
                        <button name="subscribe" class="subscribe_button" type="button">Subscribe</button>
                    </form>
                </div>
                <div class="footer_col footer_col--second">
                    <div class="footer_title">Blogs</div>
                    <div class="blogs">
                        <div class="blogs_item">
                            <img class="blogs_img" src="/image/blogs/blogs_1.jpg" alt="">
                            <div class="blogs_content">
                                <a class="blogs_title" href="#">Тенденции букетов 2021</a>
                                <div class="blogs_date">3 Июля, 2019</div>
                            </div>
                        </div>
                        <div class="blogs_item">
                            <img class="blogs_img" src="/image/blogs/blogs_2.jpg" alt="">
                            <div class="blogs_content">
                                <a class="blogs_title" href="#">Путешествие в Прованс</a>
                                <div class="blogs_date">25 Августа, 2019</div>
                            </div>
                        </div>
                        <div class="blogs_item">
                            <img class="blogs_img" src="/image/blogs/blogs_3.jpg" alt="">
                            <div class="blogs_content">
                                <a class="blogs_title" href="#">Что нужно чтобы стать флористом</a>
                                <div class="blogs_date">11 Сентября, 2020</div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="footer_col footer_col--third">
                    <div class="footer_title">Instagram</div>

                    <div class="instagram">
                        <a class="instagram_item" href="#" target="_blank">
                            <img src="/image/inst/inst_1.jpg" alt="">
                        </a>
                        <a class="instagram_item" href="#" target="_blank">
                            <img src="/image/inst/inst_2.jpg" alt="">
                        </a>
                        <a class="instagram_item" href="#" target="_blank">
                            <img src="/image/inst/inst_3.jpg" alt="">
                        </a>
                        <a class="instagram_item" href="#" target="_blank">
                            <img src="/image/inst/inst_4.jpg" alt="">
                        </a>
                        <a class="instagram_item" href="#" target="_blank">
                            <img src="/image/inst/inst_5.jpg" alt="">
                        </a>
                        <a class="instagram_item" href="#" target="_blank">
                            <img src="/image/inst/inst_6.jpg" alt="">
                        </a>
                        <a class="instagram_item" href="#" target="_blank">
                            <img src="/image/inst/inst_7.jpg" alt="">
                        </a>
                        <a class="instagram_item" href="#" target="_blank">
                            <img src="/image/inst/inst_8.jpg" alt="">
                        </a>
                        <a class="instagram_item" href="#" target="_blank">
                            <img src="/image/inst/inst_9.jpg" alt="">
                        </a>
                    </div>
                </div>
            </div>
            <div class="copyright">
                © 2020 Flower by <span>Anastasia</span>
            </div>
        </div>
    </footer>
</body>
</html>