<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Flowers</title>
    <link href="https://fonts.googleapis.com/css2?family=Kaushan+Script&family=Montserrat:wght@400;700&display=swap"
          rel="stylesheet">
    <link rel="stylesheet" href="/css/main.css">
    <script src="https://kit.fontawesome.com/c02ef43b18.js" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.js"
            integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc="
            crossorigin="anonymous"></script>
</head>
<body>
<header class="header">
    <div class="container">
        <div class="header_inner">
            <a class="header_logo" href="/main">.flower</a>
            <nav class="nav">
                <a class="nav_link" href="/aboutUs">О нас</a>
                <a class="nav_link" href="/shop">Купить</a>
                <a class="nav_link" href="/blog">Блог</a>
                <a class="nav_link" href="/works">Работы</a>
                <a class="nav_link" href="/contact">Контакты</a>
                <a class="nav_link" href="/basket">
                    <i class="fas fa-shopping-cart"></i>
                </a>
                <a class="nav_link signIn" href="/signIn">
                    <i class="fas fa-user"></i>
                </a>
            </nav>
            <button class="nav-toggle active" type="button">
                <span class="nav-toggle_item"></span>
            </button>
        </div>
    </div>
</header>

<div class="intro">
    <div class="container">
        <div class="intro_inner">
            <h2 class="intro_suptitle">Только у нас</h2>
            <h1 class="intro_title">Букеты цветов</h1>

            <a class="btn" href="#">Узнать больше</a>
        </div>
    </div>
</div>

<section class="section">
    <div class="container">
        <div class="section_header">
            <h3 class="section_subtitle">Что мы делаем</h3>
            <h4 class="section_title">Наша истроия</h4>
            <div class="section_text">
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut
                    labore
                    et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.</p>
            </div>
        </div>

        <div class="card">
            <div class="card_item">
                <div class="card_inner">
                    <div class="card_image">
                        <img src="/image/about/1.jpg">
                    </div>
                    <div class="card_text">super team</div>
                </div>
            </div>
            <div class="card_item">
                <div class="card_inner">
                    <div class="card_image">
                        <img src="/image/about/2.jpg">
                    </div>
                    <div class="card_text">super team</div>
                </div>
            </div>
            <div class="card_item">
                <div class="card_inner">
                    <div class="card_image">
                        <img src="/image/about/3.jpg">
                    </div>
                    <div class="card_text">super team</div>
                </div>
            </div>
        </div>
    </div>
</section>

<div class="statistic">
    <div class="container">
        <div class="stat">
            <div class="stat_item">
                <div class="stat_count">42</div>
                <div class="stat_text">Web design projects</div>
            </div>
            <div class="stat_item">
                <div class="stat_count">42</div>
                <div class="stat_text">Web design projects</div>
            </div>
            <div class="stat_item">
                <div class="stat_count">42</div>
                <div class="stat_text">Web design projects</div>
            </div>
            <div class="stat_item">
                <div class="stat_count">42</div>
                <div class="stat_text">Web design projects</div>
            </div>
            <div class="stat_item">
                <div class="stat_count">42</div>
                <div class="stat_text">Web design projects</div>
            </div>
        </div>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <div class="footer_inner">
            <div class="footer_col footer_col--first">
                <div class="footer_logo">Цветы</div>
                <div class="footer_text">Текст Текст Текст Текст Текст Текст Текст Текст Текст Текст Текст Текст
                    Текст
                    Текст Текст Текст Текст Текст Текст Текст Текст Текст Текст Текст Текст Текст Текст Текст Текст
                    Текст Текст Текст Текст
                </div>
                <div class="footer_social">
                    <div class="footer_social-header">
                        <b>15k folowers</b>
                    </div>
                    <div class="footer_social-content">
                        Follow us:
                        <a href="#" target="_blank">
                            <i class="fab fa-facebook"></i>
                        </a>
                        <a href="#" target="_blank">
                            <i class="fab fa-twitter"></i>
                        </a>
                        <a href="#" target="_blank">
                            <i class="fab fa-instagram"></i>
                        </a>
                    </div>
                </div>

                <div class="subscribe">
                    <form action="/main" method="post">
                        <input class="subscribe_input" type="email" name="email" placeholder="email">
                        <input name="subscribe" class="subscribe_button" value="Subscribe" type="submit">
                    </form>
                </div>

            </div>
            <div class="footer_col footer_col--second">
                <div class="footer_title">Blogs</div>
                <div class="blogs">
                    <div class="blogs_item">
                        <img class="blogs_img" src="/image/blogs/blogs_1.jpg" alt="">
                        <div class="blogs_content">
                            <a class="blogs_title" href="#">Тенденции букетов 2021</a>
                            <div class="blogs_date">3 Июля, 2019</div>
                        </div>
                    </div>
                    <div class="blogs_item">
                        <img class="blogs_img" src="/image/blogs/blogs_2.jpg" alt="">
                        <div class="blogs_content">
                            <a class="blogs_title" href="#">Путешествие в Прованс</a>
                            <div class="blogs_date">25 Августа, 2019</div>
                        </div>
                    </div>
                    <div class="blogs_item">
                        <img class="blogs_img" src="/image/blogs/blogs_3.jpg" alt="">
                        <div class="blogs_content">
                            <a class="blogs_title" href="#">Что нужно чтобы стать флористом</a>
                            <div class="blogs_date">11 Сентября, 2020</div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="footer_col footer_col--third">
                <div class="footer_title">Instagram</div>

                <div class="instagram">
                    <a class="instagram_item" href="#" target="_blank">
                        <img src="/image/inst/inst_1.jpg" alt="">
                    </a>
                    <a class="instagram_item" href="#" target="_blank">
                        <img src="/image/inst/inst_2.jpg" alt="">
                    </a>
                    <a class="instagram_item" href="#" target="_blank">
                        <img src="/image/inst/inst_3.jpg" alt="">
                    </a>
                    <a class="instagram_item" href="#" target="_blank">
                        <img src="/image/inst/inst_4.jpg" alt="">
                    </a>
                    <a class="instagram_item" href="#" target="_blank">
                        <img src="/image/inst/inst_5.jpg" alt="">
                    </a>
                    <a class="instagram_item" href="#" target="_blank">
                        <img src="/image/inst/inst_6.jpg" alt="">
                    </a>
                    <a class="instagram_item" href="#" target="_blank">
                        <img src="/image/inst/inst_7.jpg" alt="">
                    </a>
                    <a class="instagram_item" href="#" target="_blank">
                        <img src="/image/inst/inst_8.jpg" alt="">
                    </a>
                    <a class="instagram_item" href="#" target="_blank">
                        <img src="/image/inst/inst_9.jpg" alt="">
                    </a>
                </div>
            </div>
        </div>
        <div class="copyright">
            © 2020 Flower by <span>Anastasia</span>
        </div>
    </div>
</footer>
</body>
</html>