<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Shop</title>
    <link href="https://fonts.googleapis.com/css2?family=Kaushan+Script&family=Montserrat:wght@400;700&display=swap"
          rel="stylesheet">
    <link rel="stylesheet" href="../css/shop.css">
    <script src="https://kit.fontawesome.com/c02ef43b18.js" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.js"
            integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc="
            crossorigin="anonymous"></script>
</head>
<body>
<header class="header">
    <div class="container">
        <div class="header_inner">
            <div class="header_logo">.flower</div>
            <nav class="nav">
                <a class="nav_link" href="/aboutUs">О нас</a>
                <a class="nav_link" href="/shop">Купить</a>
                <a class="nav_link" href="/blog">Блог</a>
                <a class="nav_link" href="/works">Работы</a>
                <a class="nav_link" href="/contact">Контакты</a>
                <a class="nav_link" href="#">
                    <i class="fas fa-shopping-cart"></i>
                </a>
                <a class="nav_link signIn" href="/signIn">
                    <i class="fas fa-user"></i>
                </a>
            </nav>
        </div>
    </div>
</header>

<div class="title">Выберите категорию</div>

<div class="products">
    <div class="container">
        <div class="container content">
            <div class="row">
                <div class="col-md-4">
                    <div class="list-group">
                        <a href="#" class="list-group-item bouquet">Букеты</a>
                        <a href="#" class="list-group-item flower">Цветы</a>
                        <a href="#" class="list-group-item toy">Игрушки</a>
                        <a href="#" class="list-group-item decorate">Украшения</a>
                    </div>
                </div>
                <div class="col-md-8"></div>
            </div>
        </div>
        <div class="bouquets">
            <div class="product">
                <div class="product-wrap">
                    <div class="product-item">
                        <img src="/image/shop/bouquets/1.jpg">
                        <div class="product-buttons">
                            <a href="" class="button">В корзину</a>
                        </div>
                    </div>
                    <div class="product-title">
                        <p>Title</p>
                        <span class="product-price">1999 руб</span>
                    </div>
                </div>
                <div class="product-wrap">
                    <div class="product-item">
                        <img src="/image/shop/bouquets/2.jpg">
                        <div class="product-buttons">
                            <a href="" class="button">В корзину</a>
                        </div>
                    </div>
                    <div class="product-title">
                        <p>Title</p>
                        <span class="product-price">1999 руб</span>
                    </div>
                </div>
                <div class="product-wrap">
                    <div class="product-item">
                        <img src="/image/shop/bouquets/3.jpg">
                        <div class="product-buttons">
                            <a href="" class="button">В корзину</a>
                        </div>
                    </div>
                    <div class="product-title">
                        <p>Title</p>
                        <span class="product-price">1999 руб</span>
                    </div>
                </div>
                <div class="product-wrap">
                    <div class="product-item">
                        <img src="/image/shop/bouquets/4.jpg">
                        <div class="product-buttons">
                            <a href="" class="button">В корзину</a>
                        </div>
                    </div>
                    <div class="product-title">
                        <p>Title</p>
                        <span class="product-price">1999 руб</span>
                    </div>
                </div>
            </div>
            <div class="product">
                <div class="product-wrap">
                    <div class="product-item">
                        <img src="/image/shop/bouquets/5.jpg">
                        <div class="product-buttons">
                            <a href="" class="button">В корзину</a>
                        </div>
                    </div>
                    <div class="product-title">
                        <p>Title</p>
                        <span class="product-price">1999 руб</span>
                    </div>
                </div>
                <div class="product-wrap">
                    <div class="product-item">
                        <img src="/image/shop/bouquets/6.jpg">
                        <div class="product-buttons">
                            <a href="" class="button">В корзину</a>
                        </div>
                    </div>
                    <div class="product-title">
                        <p>Title</p>
                        <span class="product-price">1999 руб</span>
                    </div>
                </div>
                <div class="product-wrap">
                    <div class="product-item">
                        <img src="/image/shop/bouquets/7.jpg">
                        <div class="product-buttons">
                            <a href="" class="button">В корзину</a>
                        </div>
                    </div>
                    <div class="product-title">
                        <p>Title</p>
                        <span class="product-price">1999 руб</span>
                    </div>
                </div>
                <div class="product-wrap">
                    <div class="product-item">
                        <img src="/image/shop/bouquets/8.jpg">
                        <div class="product-buttons">
                            <a href="" class="button">В корзину</a>
                        </div>
                    </div>
                    <div class="product-title">
                        <p>Title</p>
                        <span class="product-price">1999 руб</span>
                    </div>
                </div>
            </div>
        </div>
        <div class="flowers">
            <div class="product">
                <div class="product-wrap">
                    <div class="product-item">
                        <img src="/image/shop/flowers/5.jpg">
                        <div class="product-buttons">
                            <a href="" class="button">В корзину</a>
                        </div>
                    </div>
                    <div class="product-title">
                        <p>Роза</p>
                        <span class="product-price">1999 руб</span>
                    </div>
                </div>
                <div class="product-wrap">
                    <div class="product-item">
                        <img src="/image/shop/flowers/6.jpg">
                        <div class="product-buttons">
                            <a href="" class="button">В корзину</a>
                        </div>
                    </div>
                    <div class="product-title">
                        <p>Тюльпан</p>
                        <span class="product-price">1999 руб</span>
                    </div>
                </div>
                <div class="product-wrap">
                    <div class="product-item">
                        <img src="/image/shop/flowers/7.jpg">
                        <div class="product-buttons">
                            <a href="" class="button">В корзину</a>
                        </div>
                    </div>
                    <div class="product-title">
                        <p>Гипсофил</p>
                        <span class="product-price">1999 руб</span>
                    </div>
                </div>
                <div class="product-wrap">
                    <div class="product-item">
                        <img src="/image/shop/flowers/8.jpeg">
                        <div class="product-buttons">
                            <a href="" class="button">В корзину</a>
                        </div>
                    </div>
                    <div class="product-title">
                        <p>Хризантема</p>
                        <span class="product-price">1999 руб</span>
                    </div>
                </div>
            </div>
            <div class="product">
                <div class="product-wrap">
                    <div class="product-item">
                        <img src="/image/shop/flowers/5.jpg">
                        <div class="product-buttons">
                            <a href="" class="button">В корзину</a>
                        </div>
                    </div>
                    <div class="product-title">
                        <p>Лилия</p>
                        <span class="product-price">1999 руб</span>
                    </div>
                </div>
                <div class="product-wrap">
                    <div class="product-item">
                        <img src="/image/shop/flowers/6.jpg">
                        <div class="product-buttons">
                            <a href="" class="button">В корзину</a>
                        </div>
                    </div>
                    <div class="product-title">
                        <p>Гвоздика</p>
                        <span class="product-price">1999 руб</span>
                    </div>
                </div>
                <div class="product-wrap">
                    <div class="product-item">
                        <img src="/image/shop/flowers/7.jpg">
                        <div class="product-buttons">
                            <a href="" class="button">В корзину</a>
                        </div>
                    </div>
                    <div class="product-title">
                        <p>Ромашка</p>
                        <span class="product-price">1999 руб</span>
                    </div>
                </div>
                <div class="product-wrap">
                    <div class="product-item">
                        <img src="/image/shop/flowers/8.jpg">
                        <div class="product-buttons">
                            <a href="" class="button">В корзину</a>
                        </div>
                    </div>
                    <div class="product-title">
                        <p>Гербера</p>
                        <span class="product-price">1999 руб</span>
                    </div>
                </div>
            </div>
        </div>
        <div class="toys">
            <div class="product">
                <div class="product-wrap">
                    <div class="product-item">
                        <img src="/image/shop/toys/9.jpg">
                        <div class="product-buttons">
                            <a href="" class="button">В корзину</a>
                        </div>
                    </div>
                    <div class="product-title">
                        <p>Title</p>
                        <span class="product-price">1999 руб</span>
                    </div>
                </div>
                <div class="product-wrap">
                    <div class="product-item">
                        <img src="/image/shop/toys/10.jpg">
                        <div class="product-buttons">
                            <a href="" class="button">В корзину</a>
                        </div>
                    </div>
                    <div class="product-title">
                        <p>Title</p>
                        <span class="product-price">1999 руб</span>
                    </div>
                </div>
                <div class="product-wrap">
                    <div class="product-item">
                        <img src="/image/shop/toys/11.jpg">
                        <div class="product-buttons">
                            <a href="" class="button">В корзину</a>
                        </div>
                    </div>
                    <div class="product-title">
                        <p>Title</p>
                        <span class="product-price">1999 руб</span>
                    </div>
                </div>
                <div class="product-wrap">
                    <div class="product-item">
                        <img src="/image/shop/toys/12.jpg">
                        <div class="product-buttons">
                            <a href="" class="button">В корзину</a>
                        </div>
                    </div>
                    <div class="product-title">
                        <p>Title</p>
                        <span class="product-price">1999 руб</span>
                    </div>
                </div>
            </div>
            <div class="product">
                <div class="product-wrap">
                    <div class="product-item">
                        <img src="/image/shop/toys/5.jpg">
                        <div class="product-buttons">
                            <a href="" class="button">В корзину</a>
                        </div>
                    </div>
                    <div class="product-title">
                        <p>Title</p>
                        <span class="product-price">1999 руб</span>
                    </div>
                </div>
                <div class="product-wrap">
                    <div class="product-item">
                        <img src="/image/shop/toys/6.jpg">
                        <div class="product-buttons">
                            <a href="" class="button">В корзину</a>
                        </div>
                    </div>
                    <div class="product-title">
                        <p>Title</p>
                        <span class="product-price">1999 руб</span>
                    </div>
                </div>
                <div class="product-wrap">
                    <div class="product-item">
                        <img src="/image/shop/toys/7.jpg">
                        <div class="product-buttons">
                            <a href="" class="button">В корзину</a>
                        </div>
                    </div>
                    <div class="product-title">
                        <p>Title</p>
                        <span class="product-price">1999 руб</span>
                    </div>
                </div>
                <div class="product-wrap">
                    <div class="product-item">
                        <img src="/image/shop/toys/8.jpg">
                        <div class="product-buttons">
                            <a href="" class="button">В корзину</a>
                        </div>
                    </div>
                    <div class="product-title">
                        <p>Title</p>
                        <span class="product-price">1999 руб</span>
                    </div>
                </div>
            </div>
        </div>
        <div class="decorating">
            <div class="product">
                <div class="product-wrap">
                    <div class="product-item">
                        <img src="/image/shop/decorating/13.jpg">
                        <div class="product-buttons">
                            <a href="" class="button">В корзину</a>
                        </div>
                    </div>
                    <div class="product-title">
                        <p>Title</p>
                        <span class="product-price">1999 руб</span>
                    </div>
                </div>
                <div class="product-wrap">
                    <div class="product-item">
                        <img src="/image/shop/decorating/14.jpg">
                        <div class="product-buttons">
                            <a href="" class="button">В корзину</a>
                        </div>
                    </div>
                    <div class="product-title">
                        <p>Title</p>
                        <span class="product-price">1999 руб</span>
                    </div>
                </div>
                <div class="product-wrap">
                    <div class="product-item">
                        <img src="/image/shop/decorating/15.jpg">
                        <div class="product-buttons">
                            <a href="" class="button">В корзину</a>
                        </div>
                    </div>
                    <div class="product-title">
                        <p>Title</p>
                        <span class="product-price">1999 руб</span>
                    </div>
                </div>
                <div class="product-wrap">
                    <div class="product-item">
                        <img src="/image/shop/decorating/16.jpg">
                        <div class="product-buttons">
                            <a href="" class="button">В корзину</a>
                        </div>
                    </div>
                    <div class="product-title">
                        <p>Title</p>
                        <span class="product-price">1999 руб</span>
                    </div>
                </div>
            </div>
            <div class="product">
                <div class="product-wrap">
                    <div class="product-item">
                        <img src="/image/shop/decorating/5.jpg">
                        <div class="product-buttons">
                            <a href="" class="button">В корзину</a>
                        </div>
                    </div>
                    <div class="product-title">
                        <p>Title</p>
                        <span class="product-price">1999 руб</span>
                    </div>
                </div>
                <div class="product-wrap">
                    <div class="product-item">
                        <img src="/image/shop/decorating/6.jpg">
                        <div class="product-buttons">
                            <a href="" class="button">В корзину</a>
                        </div>
                    </div>
                    <div class="product-title">
                        <p>Title</p>
                        <span class="product-price">1999 руб</span>
                    </div>
                </div>
                <div class="product-wrap">
                    <div class="product-item">
                        <img src="/image/shop/decorating/7.jpg">
                        <div class="product-buttons">
                            <a href="" class="button">В корзину</a>
                        </div>
                    </div>
                    <div class="product-title">
                        <p>Title</p>
                        <span class="product-price">1999 руб</span>
                    </div>
                </div>
                <div class="product-wrap">
                    <div class="product-item">
                        <img src="/image/shop/decorating/8.jpg">
                        <div class="product-buttons">
                            <a href="" class="button">В корзину</a>
                        </div>
                    </div>
                    <div class="product-title">
                        <p>Title</p>
                        <span class="product-price">1999 руб</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function () {
        var bouquet = $('.bouquet');
        var toy = $('.toy');
        var flower = $('.flower');
        var decorate = $('.decorate');
        var bouquets = $('.bouquets');
        var toys = $('.toys');
        var flowers = $('.flowers');
        var decorating = $('.decorating');

        bouquet.click(function () {
            bouquets.toggleClass('bouquets_active');
            toys.removeClass('toys_active');
            flowers.removeClass('flowers_active');
            decorating.removeClass('decorating_active');
        });

        toy.click(function () {
            toys.toggleClass('toys_active');
            bouquets.removeClass('bouquets_active');
            flowers.removeClass('flowers_active');
            decorating.removeClass('decorating_active');
        });

        flower.click(function () {
            flowers.toggleClass('flowers_active');
            bouquets.removeClass('bouquets_active');
            toys.removeClass('toys_active');
            decorating.removeClass('decorating_active');
        });

        decorate.click(function () {
            decorating.toggleClass('decorating_active');
            bouquets.removeClass('bouquets_active');
            toys.removeClass('toys_active');
            flowers.removeClass('flowers_active');
        });

    });
</script>

</body>
</html>