<html>
<head>
    <meta charset="UTF-8">
    <title>Works</title>
    <link rel="stylesheet" href="/css/works.css">
    <link href="https://fonts.googleapis.com/css2?family=Kaushan+Script&family=Montserrat:ital,wght@0,400;0,700;1,300&display=swap"
          rel="stylesheet">
    <script src="https://kit.fontawesome.com/c02ef43b18.js" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.js"
            integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc="
            crossorigin="anonymous"></script>
</head>

<body>
    <header class="header">
        <div class="container">
            <div class="header_inner">
                <a class="header_logo" href="/main">.flower</a>
                <nav class="nav">
                    <a class="nav_link" href="/aboutUs">О нас</a>
                    <a class="nav_link" href="/shop">Купить</a>
                    <a class="nav_link" href="/blog">Блог</a>
                    <a class="nav_link" href="/works">Работы</a>
                    <a class="nav_link" href="/contact">Контакты</a>
                    <a class="nav_link" href="/basket">
                        <i class="fas fa-shopping-cart"></i>
                    </a>
                    <a class="nav_link signIn" href="/signIn">
                        <i class="fas fa-user"></i>
                    </a>
                </nav>
            </div>
        </div>
    </header>

    <div class="gallery">
        <div class="container">
            <div class="gallery_header">
                <div class="gallery_item">
                    <img class="gallery_photo" src="/image/works/works_1.jpg" alt="">
                </div>
                <div class="gallery_item">
                    <img class="gallery_photo" src="/image/works/works_2.jpg" alt="">
                </div>
                <div class="gallery_item">
                    <img class="gallery_photo" src="/image/works/works_3.jpg" alt="">
                </div>
            </div>
            <div class="gallery_header">
                <div class="gallery_item">
                    <img class="gallery_photo" src="/image/works/works_4.jpg" alt="">
                </div>
                <div class="gallery_item">
                    <img class="gallery_photo" src="/image/works/works_5.jpg" alt="">
                </div>
                <div class="gallery_item">
                    <img class="gallery_photo" src="/image/works/works_6.jpg" alt="">
                </div>
            </div>
            <div class="gallery_header">
                <div class="gallery_item">
                    <img class="gallery_photo" src="/image/works/works_7.jpg" alt="">
                </div>
                <div class="gallery_item">
                    <img class="gallery_photo" src="/image/works/works_8.jpeg" alt="">
                </div>
                <div class="gallery_item">
                    <img class="gallery_photo" src="/image/works/works_9.jpg" alt="">
                </div>
            </div>
        </div>
    </div>

</body>
</html>
